server:
  port: 8003
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    order-server:  #路由的id，随意写
      path: /order/**  #映射路径
      serviceId: order-server #配置转发的微服务的名称
    user-server:
      path: /user/**
      serviceId: user-server
    school-server:
      path: /school/**
      serviceId: school-server
    curriculum-server:
      path: /curriculum/**
      serviceId: curriculum-server


#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000